### ISSUE TITLE
failed to build for ghidra 10.2.x

### ISSUE THREAD

**Issue by SquallATF** [kotcrab/ghidra-allegrex#20]
The debuger interface has changed https://github.com/NationalSecurityAgency/ghidra/commit/cb16d8dd9e70363d28f08b8d706f13f5a325efc3

**Comment by kotcrab** [comment]
Yep though debugger is simple to update. What's worse they also changed relocation handling which will require some refactors. I've done some work on https://github.com/kotcrab/ghidra-allegrex/tree/10.2-wip but it's not done. So for now we are stuck on 10.1.x.
