### ISSUE TITLE
Import File - Uncaught Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Nemoumbra** [kotcrab/ghidra-allegrex#21]
![image](https://user-images.githubusercontent.com/62447396/210412219-bd51bc01-cd60-47a4-a50a-726eef01c678.png)

Context: I tried to import the eboot.bin file of Patapon 3 EUR.
The version is "Allegrex-Ghidra-10.1.5" from the latest release.

**Comment by Mc-muffin** [comment]
> Ghidra version 10.2.2

There's your problem, there's no 10.2.X version yet, try with 10.1.5 which is the latest Ghidra version that the extension supports

**Comment by kotcrab** [comment]
Yes, you need to use same Ghidra version as in the extension file name. 
This is covered by #20.
