### ISSUE TITLE
Export to ELF unsupported

### ISSUE THREAD

**Issue by archanox** [kotcrab/ghidra-allegrex#24]
When trying to export to an ELF for using with psp-gdb for adding debugging symbols, Ghidra states that the PSP Executable is an unsupported format.

![Screenshot 2023-04-02 at 12 35 25 pm](https://user-images.githubusercontent.com/1642971/229328080-3317f726-26af-4630-97ce-c2da9615a970.png)

**Comment by kotcrab** [comment]
I'm not sure why you would need this. I don't think it will be supported unless someone is willing to contribute this.

**Comment by archanox** [comment]
I'm trying to get debug symbols over to psp-gdb so the breakpoints are functional with it. The alternative (in my limited understanding) is that I'd export DWARF files but that is also unsupported I'm lead to believe.

**Comment by kotcrab** [comment]
To export as ELF you need to use option to export `Original File` with also has option to export user modifications:

![image](https://github.com/kotcrab/ghidra-allegrex/assets/4594081/f75796d5-bdb3-4734-ae4a-070c15521817)
