### ISSUE TITLE
Type A relocations are not currently supported for ELFs without sections. Please report this.

### ISSUE THREAD

**Issue by Mc-muffin** [kotcrab/ghidra-allegrex#28]
Just got this while loading a game, so I guess I'm reporting it :)

**Comment by Mc-muffin** [comment]
I'll add more info now that I researched a little:
- Game is Danganronpa 2 (NPJH50515)
- Ghidra 10.2.3
- Java JDK 20 (Oracle)
- The elf header indeed lists `e_shnum` as 0

Digging through PPSSPP's source it seems like supporting these might be simple, check: https://github.com/hrydgard/ppsspp/blob/master/Core/ELF/ElfReader.cpp#L643

It just scans for a sections with `p_type` set as `0x700000A0` (they call it `PT_PSPREL1`, which I guess are type-A relocs), then it just consumes the whole segment as a big array of relocation info.

**Comment by Mc-muffin** [comment]
Would also be cool if we could recover the NID related sections (`.lib.ent`, `.lib.stub`, `.rodata.sceModuleInfo`, `.rodata.sceResident` and `.rodata.sceNid`) so we can use the NIDresolver script on these programs too.

Recovering any other section (say `.rodata`, `.ctors`, `.dtors`, `.eh_frame` etc) would be entirely optional

**Comment by kotcrab** [comment]
Duplicate of #25, should be already fixed in v16, you will need to update your Ghidra too.

Feel free to create separate issue for your last comment. Personally, I don't know how those sections could be recovered.

**Comment by Mc-muffin** [comment]
Ah, didn't catch there was an issue for this already, I guess I'll need to update.
I'll close once I can confirm it's fixed (and open an issue for the last comment, as per your suggestion)

**Comment by Mc-muffin** [comment]
Can confirm v16 fixes the problem, though, I suggest that the relocation segment is either named as such or that the relocation structs appear inside so people know what the segment is for.

Otherwise it's working as intended, thanks!
