### ISSUE TITLE
Ghidra 11.1 support

### ISSUE THREAD

**Issue by Nemoumbra** [kotcrab/ghidra-allegrex#41]
I have noticed that the newly released version introduces a different Debugger API that somehow uses Python 3. Please investigate if the plugin requires some Java <-> Python bindings for the new debugger protocol to operate.
Considering I've been making attempts at creating a Python library for communicating with PPSSPP... I'm very intrigued.

Of course, we'll have to revisit the issue about the Allegrex Debugger's workflow... But it's for later.

**Comment by kotcrab** [comment]
Looks like Ghidra is removing the `DebuggerObjectModel` approach and is replacing it with Trace RMI. This will require full rewrite of the integration. Sounds like it has to be done in Python or maybe the client can be directly implemented in PPSSPP (maybe that would provide better experience). Either way I'm not really planning to do it. I'll remove the integration once they fully kill `DebuggerObjectModel`. For now it still seems usable, although requires enabling disabled plugins for the default Debugger tool.

**Comment by kotcrab** [comment]
Snapshot is built, I'm planning to do #8 in this release.

**Comment by kotcrab** [comment]
https://github.com/kotcrab/ghidra-allegrex/releases/tag/v19
